<?php

$title = 'Delete user';
$url   = $this->url('user', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($user->firstname) ?> <?= $this->escapeHtml($user->lastname) ?>"?
</p>


<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= $user->id ?>" />
        <?php
        if($showBtn) {
        ?>
            <input type="submit" class="btn btn-danger" name="del" value="Yes" />
            <input type="submit" class="btn btn-success" name="del" value="No" />
        <?php
        }
        ?>
    </div>
</form>