<?php

$title = 'Edit user';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$firstname = $form->get('firstname');
$firstname->setAttribute('class', 'form-control');
$firstname->setAttribute('placeholder', 'User first name');

$lastname = $form->get('lastname');
$lastname->setAttribute('class', 'form-control');
$lastname->setAttribute('placeholder', 'User last name');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'User email');

$position = $form->get('position');
$position->setAttribute('class', 'form-control');
$position->setAttribute('placeholder', 'User position');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', [
        'action'    => 'edit',
        'id'        => $id
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($firstname) ?>
        <?= $this->formElement($firstname) ?>
        <?= $this->formElementErrors()->render($firstname, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($lastname) ?>
        <?= $this->formElement($lastname) ?>
        <?= $this->formElementErrors()->render($lastname, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($position) ?>
        <?= $this->formElement($position) ?>
        <?= $this->formElementErrors()->render($position, ['class' => 'help-block']) ?>
    </div>
<?php
if($showBtn) {
    echo $this->formSubmit($submit);
}
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('csrf'));
echo $this->form()->closeTag();

