<div class="row">
    <div class="col-sm-12">
        <a class="btn btn-primary btn-new-user" data-action-btn="true" data-action-btn-class="btn-primary" data-action-btn-title="Add"  href="<?= $this->url('user', ['action' => 'add']) ?>">New</a>
    </div>
</div>
<hr>
<table class="table dataTable">
    <thead>
    <tr>
        <th>#</th>
        <th>firstname</th>
        <th>lastname</th>
        <th>email</th>
        <th>position</th>
        <th>action</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>

