<ul class="nav navbar-nav">
    <?php
    foreach ($this->container as $page) {
        $hasChildren = $page->hasPages();
        if( ! $hasChildren) {
            ?>
            <li
                <?php
                if($page->isActive()){
                    echo 'class="active"';
                }
                ?>
            ><a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel();?></a></li>
            <?php
        }
        else {
            ?>
            <li
                <?php
                if($page->isActive()){
                    echo 'class="dropdown active"';
                } else {
                    echo 'class="dropdown"';
                }
                ?>
            >
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $page->getLabel(); ?> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <?php
                    foreach($page->getPages() as $child)
                    {
                        ?>
                        <li><a href="<?php echo $child->getHref(); ?>"><?php echo $child->getLabel(); ?></a></li>
                        <?php
                    }
                    ?>
                </ul>
            </li>
            <?php
        }
    }
    ?>
</ul>